### ISSUE TITLE
It is not an issue, but may be you interest :)

### ISSUE THREAD

**Issue by FerhatOzkanun** [kodybrown/sortxml#2]
Hi, I recently reached your sortXml app. It is very good to simple usage. 

BTW, I kindly edited it and added a UI for dummies (like me). It already works as console application. With stand-alone UI by desktop.

If you interested in, I would love to send its link to you. This is my mail adres: luckystar27@mynet.com. Also you can input a message from our web-site, so it is: http://pspyazilim.com.tr/Contents/iletisim.

And also I need to discuss some subjects (there is nothing as precise for now) with programmers like you.
Anyway, thank you for reading this :)
as the attachment, I send a shot.
![screenshot_1](https://cloud.githubusercontent.com/assets/22818972/19354663/35f54d2a-9170-11e6-8295-50158d744aa5.png)

**Comment by akirayamamoto** [comment]
Why don't you make a pull request?

**Comment by FerhatOzkanun** [comment]
"Create Pull Request" button was disabled. So, I couldn't.
